export const FETCH_STUDENTS_REQUEST = "FETCH_STUDENTS_REQUEST";
export const FETCH_STUDENTS_SUCCESS = "FETCH_STUDENTS_SUCCESS";
export const FETCH_STUDENTS_FAILURE = "FETCH_STUDENTS_FAILURE";
export const ADD_STUDENT = "ADD_STUDENT"; //pass in a student object plzexport 
export const POST_STUDENT = "ADD_STUDENT";